#!/bin/bash

set -e

if [ -e ".env" ]; then
    source .env
fi

git pull
GIT_HASH=$(git rev-parse --short HEAD)

echo "Creating images"
docker-compose build

echo "creating containers"
docker-compose up --no-start

echo "copy static files"
docker cp  star-burger_static_1:/usr/app/staticfiles /opt/star-burger/star-burger
docker cp  star-burger_frontend:/usr/app/bundles /opt/star-burger/star-burger

echo "Restart Gunicorn"
systemctl restart star-burger.service

echo "Deployed"

if [ -v ROLLBAR_KEY ]; then 
   curl -H "X-Rollbar-Access-Token: ${ROLLBAR_KEY}" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "{\"environment\": \"production\", \"revision\": \"${GIT_HASH}\", \"rollbar_name\": \"Anton\", \"local_username\": \"$(whoami)\", \"comment\": \"deployment\", \"status\": \"succeeded\"}"
   echo "Sended log to LOGBAR"
fi
