# Используем базовый образ Python для бекенда
FROM python:3.10.6 AS backend

# Устанавливаем переменную среды для Python
ENV PYTHONUNBUFFERED 1

# Устанавливаем системные зависимости для бекенда
RUN apt-get update && apt-get install -y postgresql-client

# Создаем директорию для приложения внутри контейнера для бекенда
RUN mkdir /code
WORKDIR /code

# Копируем зависимости проекта для бекенда и устанавливаем их
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt

# Копируем остальные файлы проекта для бекенда
COPY . /code/

# Открываем порт, который будет прослушивать ваше приложение для бекенда
EXPOSE 8080

# Запускаем ваше приложение для бекенда при старте контейнера
CMD ["gunicorn", "--access-logfile", "-", "--workers", "3", "--bind", "0.0.0.0:8080", "star_burger.wsgi:application"]
