# Generated by Django 3.2.15 on 2023-11-21 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0016_auto_20230428_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
