# Generated by Django 3.2.15 on 2023-10-02 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230929_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=34, validators=[django.core.validators.MinValueValidator(0)], verbose_name='прежняя цена'),
            preserve_default=False,
        ),
    ]
