# Generated by Django 3.2.15 on 2023-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WM', 'Необработанный'), ('WR', 'Ожидание рестарана'), ('WC', 'Ожидание курьера'), ('CL', 'Завершён')], db_index=True, default='WM', max_length=2),
        ),
    ]
