# Generated by Django 3.2.15 on 2023-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WM', 'Необработанный'), ('WR', 'Ожидание рестарана'), ('WC', 'Ожидание курьера'), ('CL', 'Завершён')], db_index=True, default='WM', max_length=2, verbose_name='статус'),
        ),
    ]
