# Generated by Django 3.2.15 on 2023-10-04 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20231004_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='phoned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время создания заказа'),
        ),
    ]
