# Generated by Django 3.2.15 on 2023-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20231004_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('OF', 'Наличными')], db_index=True, default='ON', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
