# Generated by Django 3.2.15 on 2023-10-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20231004_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reustaurant',
            new_name='selected_reustaurant',
        ),
    ]
