# Generated by Django 3.2.15 on 2023-10-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_rename_reustaurant_order_selected_reustaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_reustaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='selected_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_items', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
