# Generated by Django 3.2.15 on 2023-10-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phoned_at',
            new_name='called_at',
        ),
    ]
