# Generated by Django 3.2.15 on 2023-10-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_rename_phoned_at_order_called_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_way',
            new_name='payment_method',
        ),
    ]
