# Generated by Django 3.2.15 on 2023-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_rename_payment_way_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('OF', 'Наличными')], db_index=True, default='OF', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
