# Generated by Django 3.2.15 on 2023-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_selected_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('OF', 'Наличными'), ('NS', 'Не указано')], db_index=True, default='NS', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
