# Generated by Django 3.2.15 on 2023-10-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_at',
            new_name='delivered_at',
        ),
    ]
